spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpalearn
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true